// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Jlv-py2vkgjoINu8iwCuC7mzvgV2dtE',
    appId: '1:132982708132:web:33cc913fda7ecae772d331',
    messagingSenderId: '132982708132',
    projectId: 'pictory-ff66d',
    authDomain: 'pictory-ff66d.firebaseapp.com',
    storageBucket: 'pictory-ff66d.firebasestorage.app',
    measurementId: 'G-5X5ZGMX9PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf04IJyzsdJrXjh7b7wQlnMN5zV9bpHQo',
    appId: '1:132982708132:android:275d58a90c6e00d072d331',
    messagingSenderId: '132982708132',
    projectId: 'pictory-ff66d',
    storageBucket: 'pictory-ff66d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbNAuGT1NHrRxV5GYilTX9tmPSoOVCStk',
    appId: '1:132982708132:ios:bbe0d444e07db5fd72d331',
    messagingSenderId: '132982708132',
    projectId: 'pictory-ff66d',
    storageBucket: 'pictory-ff66d.firebasestorage.app',
    iosBundleId: 'com.example.pictory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbNAuGT1NHrRxV5GYilTX9tmPSoOVCStk',
    appId: '1:132982708132:ios:bbe0d444e07db5fd72d331',
    messagingSenderId: '132982708132',
    projectId: 'pictory-ff66d',
    storageBucket: 'pictory-ff66d.firebasestorage.app',
    iosBundleId: 'com.example.pictory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3Jlv-py2vkgjoINu8iwCuC7mzvgV2dtE',
    appId: '1:132982708132:web:5a7d4aa92b244e5972d331',
    messagingSenderId: '132982708132',
    projectId: 'pictory-ff66d',
    authDomain: 'pictory-ff66d.firebaseapp.com',
    storageBucket: 'pictory-ff66d.firebasestorage.app',
    measurementId: 'G-FTQ1VPZHQX',
  );
}
